# This file contains all available configuration options for golangci-lint.
# The Go Language Working Group is currently working on a finalized version
# of this configuration file to share with all Hubbers.

version: "2"

linters:
  enable:
    - copyloopvar
    - depguard
    - errcheck
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  disable:
    - gochecknoglobals # we allow global variables in packages
    - gochecknoinits   # we allow inits in packages
    - goconst          # we allow repeated values to go un-const'd
    - lll              # we allow any line length
    - unparam          # we allow function calls to name unused parameters
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          deny:
            - pkg: io/ioutil
              desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/deprecated$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
