name: "Build and test"

on:
  push:
    branches: [main]
  pull_request: {}

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Run format
        run: "! make fmt | grep . || { echo 'Go not formatted'; exit 1; }"

      - name: Build program
        run: make build

      - name: Run tests
        run: make test
