name: "Build and test"

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://goproxy.githubapp.com/mod,https://proxy.golang.org/,direct
      GOPRIVATE: ''
      GONOPROXY: ''
      GONOSUMDB: github.com/github/*

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # From https://github.com/github/goproxy/blob/main/doc/user.md#set-up:
      - name: Configure Go private module access
        run: |
          echo "machine goproxy.githubapp.com login nobody password ${{ secrets.GOPROXY_TOKEN }}" >> $HOME/.netrc

      - name: Run format
        run: "! make fmt | grep . || { echo 'Go not formatted'; exit 1; }"

      - name: Build program
        run: make build

      - name: Run tests
        run: make test
