name: golangci-lint

on:
  push:

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.24"
      - name: Vendor modules for later steps.
        run: |
          go mod vendor
      - uses: golangci/golangci-lint-action@v9.2.0
        with:
          # The version of golangci-lint to use (full version with patch number)
          version: v2.8.0
          args:
            -v
